#!/bin/bash

set -x

GO_VERSION="1.19.5"

yum install -y git zsh
yum install -y vim jq aws-cli gcc rsync wget &
ARCH=$(uname -m)
GO_ARCH="amd64"
if [[ "$ARCH" == "aarch64" ]]; then
    GO_ARCH="arm64"
else
    curl -o "/tmp/rg.rpm" "https://download.copr.fedorainfracloud.org/results/carlwgeorge/ripgrep/epel-7-$ARCH/00930337-ripgrep/ripgrep-11.0.1-1.el7.$ARCH.rpm" && yum -y install /tmp/rg.rpm &
fi
curl -o "/tmp/tig.rpm" "http://download-ib01.fedoraproject.org/pub/epel/7/$ARCH/Packages/t/tig-2.4.0-1.el7.$ARCH.rpm" && yum install -y /tmp/tig.rpm &
curl -o "/tmp/go.tar.gz" "https://dl.google.com/go/go$GO_VERSION.linux-$GO_ARCH.tar.gz" && tar -C /usr/local -xzf /tmp/go.tar.gz &

cat <<EOF >>/etc/ecs/ecs.config
ECS_LOGLEVEL=info
ECS_LOG_ROLLOVER_TYPE=size
ECS_ENABLE_SPOT_INSTANCE_DRAINING=true
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=5m
ECS_LOG_MAX_FILE_SIZE_MB=3000
EOF

cat <<EOF >/home/ec2-user/.vimrc
set number mouse=a colorcolumn=80 smartindent tabstop=4 laststatus=2 nocompatible
hi Comment ctermfg=darkgray
" Remember location in file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
" Disable autoindent with Ctrl-p for pasting (insert mode only)
set pastetoggle=<C-P>
EOF

usermod --shell /bin/zsh ec2-user
cat <<\EOF >/home/ec2-user/.zshrc
autoload -Uz compinit colors add-zsh-hook
compinit -u
colors
typeset -U PATH
instanceIp=$(curl --silent http://169.254.169.254/latest/meta-data/public-ipv4)
instanceId=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)
instanceType=$(curl --silent http://169.254.169.254/latest/meta-data/instance-type)
echo "Metadata: instanceIP=$instanceIp instanceID=$instanceId instanceType=$instanceType"
PROMPT="CONTAINER INST %{$fg[blue]%}%4d%{$fg[green]%}%{$fg[red]%}%{$fg_bold[red]%} %# %{$reset_color%}"
export HISTFILE=~/.zsh_history
export HISTSIZE=7500
export SAVEHIST=30000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
# completion
zstyle ':completion:*' menu select
# oh-my-zsh style history completion
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward
bindkey '\e[3~' delete-char # 'forward' delete key
alias gd='git diff'
alias gc='git checkout'
alias gs='git status --short'
alias gu='git fetch --all --prune && git checkout master && git pull origin master --tags && git checkout -'
alias ss='sudo systemctl'
alias sj='sudo journalctl'
export GOPATH=/home/ec2-user/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export AGENT=/home/ec2-user/go/src/github.com/aws/amazon-ecs-agent
cd $AGENT
EOF


wait

# update the kernel and reboot
#if [ ! -f /etc/.kernel-ng-installed ]; then
#  amazon-linux-extras install kernel-ng
#  touch /etc/.kernel-ng-installed
#  reboot
#fi

