#!/bin/bash

GITHUB_USERNAME="sparrc"
GO_VERSION="1.15.5"

apt-get update -y && apt-get install -y make git vim gcc rsync wget awscli docker.io
apt-get install -y zsh && usermod --shell /bin/zsh admin
apt-get install -y ripgrep
apt-get install -y tig
apt-get install -y jq
ARCH=$(uname -m)
ARCH_ALT=""
if [[ "$ARCH" == "x86_64" ]]; then
    ARCH_ALT="amd64"
else
    ARCH_ALT="arm64"
fi
curl -o "/tmp/go.tar.gz" "https://dl.google.com/go/go$GO_VERSION.linux-${ARCH_ALT}.tar.gz" && tar -C /usr/local -xzf /tmp/go.tar.gz && rm /tmp/go.tar.gz &
aws s3 cp s3://cssparr-tmp/amazon-ecs-init_1.48.1-1_${ARCH_ALT}.deb /tmp/ecs.deb
dpkg -i /tmp/ecs.deb

cat <<EOF >/etc/ecs/ecs.config
ECS_LOGLEVEL=info
ECS_LOG_ROLLOVER_TYPE=size
ECS_ENABLE_SPOT_INSTANCE_DRAINING=true
EOF

cat <<EOF >/home/admin/.vimrc
set number mouse=a colorcolumn=80 smartindent tabstop=4 laststatus=2 nocompatible
hi Comment ctermfg=darkgray
" Remember location in file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
" Disable autoindent with Ctrl-p for pasting (insert mode only)
set pastetoggle=<C-P>
EOF

cat <<\EOF >/home/admin/.zshrc
autoload -Uz compinit colors add-zsh-hook
compinit -u
colors
typeset -U PATH
instanceIp=$(curl --silent http://169.254.169.254/latest/meta-data/public-ipv4)
instanceId=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)
instanceType=$(curl --silent http://169.254.169.254/latest/meta-data/instance-type)
echo "Metadata: instanceIP=$instanceIp instanceID=$instanceId instanceType=$instanceType"
PROMPT="ECS DEBIAN %{$fg[blue]%}%4d%{$fg[green]%}%{$fg[red]%}%{$fg_bold[red]%} %# %{$reset_color%}"
export HISTFILE=~/.zsh_history
export HISTSIZE=7500
export SAVEHIST=30000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
# completion
zstyle ':completion:*' menu select
# oh-my-zsh style history completion
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward
bindkey '\e[3~' delete-char # 'forward' delete key
alias gd='git diff'
alias gc='git checkout'
alias gs='git status --short'
alias gu='git fetch --all --prune && git checkout master && git pull origin master --tags && git checkout -'
alias ls='ls -Fh --color'
alias ll='ls -lvH --group-directories-first'
alias la='ll -a'
alias ss='sudo systemctl'
alias sj='sudo journalctl'
export GOPATH=/home/admin/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export AGENT=/home/admin/go/src/github.com/aws/amazon-ecs-agent
EOF

mkdir -p /home/admin/go/src/github.com/aws
cd /home/admin/go/src/github.com/aws
git clone https://github.com/$GITHUB_USERNAME/amazon-ecs-agent.git
cd amazon-ecs-agent
git checkout --track origin/dev
git config --global pull.rebase true
git config --global branch.autosetuprebase always
git remote add upstream https://github.com/aws/amazon-ecs-agent.git
git fetch --all

cd /home/admin/go/src/github.com/aws
git clone https://github.com/$GITHUB_USERNAME/amazon-ecs-init.git
cd amazon-ecs-init
git remote add upstream https://github.com/aws/amazon-ecs-init.git
git fetch --all

chown -R admin /home/admin
chgrp -R admin /home/admin
